# Since we need to run part of your test suite, most libraries will first
# need to install vendors, for example via composer.
before_commands:
    - composer install --dev
tools:
    php_cs_fixer:
        extensions:
            - php
        command: php-cs-fixer
        enabled: true
        filter:
            paths: ["app/src/*"]
        config:
            level: all
    php_cpd:
        command: phpcpd
        # Minimum number of identical lines (default: 5)
        min_lines: 5
        # Minimum number of identical tokens (default: 70)
        min_tokens: 70
        # A list of names that should be scanned (default: '*.php')
        names:
            # Default:
            - '*.php'
        # A list of excluded directories.
        excluded_dirs: ["vendor", "files"]
        enabled: true
    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            paths: ["app/src/*"]
        config:
            standard: PSR2
#    external_code_coverage:
#        timeout: 1200
