var RELANG = {};
RELANG['hr'] = {
	html: 'HTML',
	video: 'Video',
	image: 'Slika',
	table: 'Tablica',
	link: 'Poveznica',
	link_insert: 'Umetni poveznicu...',
	unlink: 'Ukloni poveznicu',
	formatting: 'Stilovi',
	paragraph: 'Paragraf',
	quote: 'Citat',
	code: 'Izvorni kod',
	header1: 'Zaglavlje 1',
	header2: 'Zaglavlje 2',
	header3: 'Zaglavlje 3',
	header4: 'Zaglavlje 4',
	bold: 'Podebljaj',
	italic: 'Nakosi',
	fontcolor: 'Boja slova',
	backcolor: 'Boja pozadine',
	unorderedlist: 'Nesortirana lista',
	orderedlist: 'Sortirana lista',	
	outdent: 'Izvuci',
	indent: 'Uvuci',
	redo: 'Korak naprijed',
	undo: 'Korak nazad',
	cut: 'Izre&#382;i',
	cancel: 'Odustani',	
	insert: 'Umetni',
	save: 'Spremi',	
	_delete: 'Izbri&scaron;i',
	insert_table: 'Umetni tablicu',		
	insert_row_above: 'Dodaj redak iznad',
	insert_row_below: 'Dodaj redak ispod',
	insert_column_left: 'Dodaj stupac lijevo',
	insert_column_right: 'Dodaj stupac desno',									
	delete_column: 'Izbri&scaron;i stupac',									
	delete_row: 'Izbri&scaron;i redak',									
	delete_table: 'Izbri&scaron;i tablicu',
	rows: 'Redaka',
	columns: 'Stupaca',	
	add_head: 'Dodaj zaglavlje',
	delete_head: 'Ukloni zaglavlje',	
	title: 'Naslov',
	image_position: 'Poravnanje',
	none: 'bez',
	left: 'lijevo',
	right: 'desno',
	image_web_link: 'Web adresa slike',
	text: 'Tekst',
	mailto: 'Email',
	web: 'Web adresa',
	video_html_code: 'Video kod',
	file: 'Datoteka',	
	upload: 'Po&scaron;alji',
	download: 'Preuzmi',
	choose: 'Odaberi',
	or_choose: 'Ili odaberi',
	drop_file_here: 'Povuci datoteku ovdje',
	align_left:	'Poravnaj lijevo',	
	align_center: 'Centriraj',
	align_right: 'Poravnaj desno',
	align_justify: 'Od ruba do ruba',
	horizontalrule: 'Horizontalna crta',
	fullscreen: 'Prikaz preko èitavog ekrana',
	deleted: 'Izbrisano',
	anchor: 'Sidro'
};
