<?php

namespace Bolt\Nut;

use Bolt\Storage\Migration\Import;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\ConfirmationQuestion;
use Symfony\Component\Finder\Finder;

/**
 * Nut database importer command.
 *
 * @author Gawain Lynch <gawain.lynch@gmail.com>
 */
class DatabaseImport extends BaseCommand
{
    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('database:import')
            ->setDescription('Import database records from a YAML or JSON file')
            ->addOption('no-interaction', 'n', InputOption::VALUE_NONE, 'Do not ask for confirmation')
            ->addOption('file',           'f', InputOption::VALUE_OPTIONAL, 'A YAML or JSON file to use for import data. Must end with .yml, .yaml or .json')
            ->addOption('directory',      'd', InputOption::VALUE_OPTIONAL, 'A source directory. YAML files generated by the export command will be parsed in order')
            ->addOption('overwrite',      null, InputOption::VALUE_OPTIONAL, 'Pass --overwrite to allow overwriting of existing records?')
        ;
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $file = $input->getOption('file');
        $directory = $input->getOption('directory');
        if (empty($file) && empty($directory)) {
            throw new \RuntimeException('One of the --file or --directory options is required.');
        }

        $files = [];
        if (!empty($directory)) {
            $finder = new Finder();
            $finder->files()
                ->in($directory)
                ->name('/\.yml/')
                ->depth('<2')
                ->sortByName()
            ;
            foreach ($finder as $source) {
                $files[] = $source->getRealPath();
            }
        }

        // If we have scanned a directory then we skip the file option
        if (!count($files)) {
            $files = $input->getOption('file');
            if (empty($files)) {
                throw new \RuntimeException('The --file option is required.');
            }
        }

        // See if we're going to continue
        if ($this->checkContinue($input) === false) {
            return 0;
        }

        // Get the Bolt Import migration object
        $import = new Import($this->app);
        if ($input->hasParameterOption('--overwrite')) {
            $import->setAllowOverwrite(true);
        }

        $import
            ->setMigrationFiles($files)
            ->checkMigrationFilesValid(true)
            ->checkMigrationFilesExist('import')
            ->importMigrationFiles()
        ;

        $failed = false;
        if ($import->getError()) {
            $this->io->error($import->getErrorMessages());
            $failed = true;
        }

        if ($import->getWarning()) {
            $this->io->warning($import->getWarningMessages());
            $failed = true;
        }

        if ($import->getNotice()) {
            $this->io->note($import->getNoticeMessages());
            $failed = true;
        }
        if ($failed) {
            $this->io->error('Aborting import!');

            return 1;
        }

        // Report finish
        $this->io->success('Records imported');
        $this->io->listing($files);

        return 0;
    }

    /**
     * Check to see if we should continue.
     *
     * @param InputInterface $input
     *
     * @return boolean
     */
    private function checkContinue(InputInterface $input)
    {
        if ($input->getOption('no-interaction')) {
            return true;
        }
        $this->io->warning('This command may overwrite or replace data in the current database.');

        return $this->io->confirm('Are you sure you want to continue with the import?', false);
    }
}
