#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->setName("Bolt console tool - Nut");
$application->setVersion($app->getVersion());

$application->add(new Bolt\Nut\Greet($app));
$application->add(new Bolt\Nut\CacheClear($app));
$application->add(new Bolt\Nut\Info($app));
$application->add(new Bolt\Nut\LogTrim($app));
$application->add(new Bolt\Nut\LogClear($app));
$application->add(new Bolt\Nut\DatabaseCheck($app));
$application->add(new Bolt\Nut\DatabaseRepair($app));
$application->add(new Bolt\Nut\TestRunner($app));
$application->run();
