CodeMirror.defineMode("javascript",function(R,p){var w,j,m,x;function E(a,d){for(var c=!1,f;null!=(f=a.next());){if(f==d&&!c)return!1;c=!c&&"\\"==f}return c}function k(a,d,c){r=a;F=c;return d}function s(a,d){var c=a.next();if('"'==c||"'"==c)return c=S(c),d.tokenize=c,c(a,d);if(/[\[\]{}\(\),;\:\.]/.test(c))return k(c);if("0"==c&&a.eat(/x/i))return a.eatWhile(/[\da-f]/i),k("number","number");if(/\d/.test(c)||"-"==c&&a.eat(/\d/))return a.match(/^\d*(?:\.\d*)?(?:[eE][+\-]?\d+)?/),k("number","number");
if("/"==c){if(a.eat("*"))return c=G,d.tokenize=c,c(a,d);if(a.eat("/"))return a.skipToEnd(),k("comment","comment");if("operator"==d.lastType||"keyword c"==d.lastType||/^[\[{}\(,;:]$/.test(d.lastType))return E(a,"/"),a.eatWhile(/[gimy]/),k("regexp","string-2");a.eatWhile(y);return k("operator",null,a.current())}if("#"==c)return a.skipToEnd(),k("error","error");if(y.test(c))return a.eatWhile(y),k("operator",null,a.current());a.eatWhile(/[\w\$_]/);var c=a.current(),f=H.propertyIsEnumerable(c)&&H[c];return f&&
"."!=d.lastType?k(f.type,f.style,c):k("variable","variable",c)}function S(a){return function(d,c){E(d,a)||(c.tokenize=s);return k("string","string")}}function G(a,d){for(var c=!1,f;f=a.next();){if("/"==f&&c){d.tokenize=s;break}c="*"==f}return k("comment","comment")}function I(a,d,c,f,b,g){this.indented=a;this.column=d;this.type=c;this.prev=b;this.info=g;null!=f&&(this.align=f)}function l(){for(var a=arguments.length-1;0<=a;a--)w.push(arguments[a])}function b(){l.apply(null,arguments);return!0}function z(a){function d(d){for(;d;d=
d.next)if(d.name==a)return!0;return!1}var c=j;c.context?(m="def",d(c.localVars)||(c.localVars={name:a,next:c.localVars})):d(c.globalVars)||(c.globalVars={name:a,next:c.globalVars})}function J(){j.context={prev:j.context,vars:j.localVars};j.localVars=T}function K(){j.localVars=j.context.vars;j.context=j.context.prev}function h(a,d){var c=function(){var c=j;c.lexical=new I(c.indented,x.column(),a,null,c.lexical,d)};c.lex=!0;return c}function e(){var a=j;a.lexical.prev&&(")"==a.lexical.type&&(a.indented=
a.lexical.indented),a.lexical=a.lexical.prev)}function i(a){return function(d){return d==a?b():";"==a?l():b(arguments.callee)}}function o(a){return"var"==a?b(h("vardef"),A,i(";"),e):"keyword a"==a?b(h("form"),g,o,e):"keyword b"==a?b(h("form"),o,e):"{"==a?b(h("}"),B,e):";"==a?b():"function"==a?b(t):"for"==a?b(h("form"),i("("),h(")"),U,i(")"),e,o,e):"variable"==a?b(h("stat"),V):"switch"==a?b(h("form"),g,h("}","switch"),i("{"),B,e,e):"case"==a?b(g,i(":")):"default"==a?b(i(":")):"catch"==a?b(h("form"),
J,i("("),L,i(")"),o,e,K):l(h("stat"),g,i(";"),e)}function g(a){return M.hasOwnProperty(a)?b(n):"function"==a?b(t):"keyword c"==a?b(N):"("==a?b(h(")"),N,i(")"),e,n):"operator"==a?b(g):"["==a?b(h("]"),u(g,"]"),e,n):"{"==a?b(h("}"),u(W,"}"),e,n):b()}function N(a){return a.match(/[;\}\)\],]/)?l():l(g)}function n(a,d){if("operator"==a)return/\+\+|--/.test(d)?b(n):"?"==d?b(g,i(":"),g):b(g);if(";"!=a){if("("==a)return b(h(")"),u(g,")"),e,n);if("."==a)return b(X,n);if("["==a)return b(h("]"),g,i("]"),e,n)}}
function V(a){return":"==a?b(e,o):l(n,i(";"),e)}function X(a){if("variable"==a)return m="property",b()}function W(a,d){if("variable"==a){if(m="property","get"==d||"set"==d)return b(Y)}else if("number"==a||"string"==a)m=a+" property";if(M.hasOwnProperty(a))return b(i(":"),g)}function Y(a){if(":"==a)return b(g);if("variable"!=a)return b(i(":"),g);m="property";return b(t)}function u(a,d){function c(f){return","==f?b(a,c):f==d?b():b(i(d))}return function(f){return f==d?b():l(a,c)}}function B(a){return"}"==
a?b():l(o,B)}function O(a){return":"==a?b(Z):l()}function Z(a){return"variable"==a?(m="variable-3",b()):l()}function A(a,d){return"variable"==a?(z(d),C?b(O,D):b(D)):l()}function D(a,d){if("="==d)return b(g,D);if(","==a)return b(A)}function U(a){return"var"==a?b(A,i(";"),v):";"==a?b(v):"variable"==a?b($):b(v)}function $(a,d){return"in"==d?b(g):b(n,v)}function v(a,d){return";"==a?b(P):"in"==d?b(g):b(g,i(";"),P)}function P(a){")"!=a&&b(g)}function t(a,d){if("variable"==a)return z(d),b(t);if("("==a)return b(h(")"),
J,u(L,")"),e,o,K)}function L(a,d){if("variable"==a)return z(d),C?b(O):b()}var q=R.indentUnit,Q=p.json,C=p.typescript,H=function(){function a(a){return{type:a,style:"keyword"}}var d=a("keyword a"),c=a("keyword b"),b=a("keyword c"),g=a("operator"),e={type:"atom",style:"atom"},d={"if":d,"while":d,"with":d,"else":c,"do":c,"try":c,"finally":c,"return":b,"break":b,"continue":b,"new":b,"delete":b,"throw":b,"var":a("var"),"const":a("var"),let:a("var"),"function":a("function"),"catch":a("catch"),"for":a("for"),
"switch":a("switch"),"case":a("case"),"default":a("default"),"in":g,"typeof":g,"instanceof":g,"true":e,"false":e,"null":e,undefined:e,NaN:e,Infinity:e,"this":a("this")};if(C){var c={type:"variable",style:"variable-3"},c={"interface":a("interface"),"class":a("class"),"extends":a("extends"),constructor:a("constructor"),"public":a("public"),"private":a("private"),"protected":a("protected"),"static":a("static"),"super":a("super"),string:c,number:c,bool:c,any:c},i;for(i in c)d[i]=c[i]}return d}(),y=/[+\-*&%=<>!?|~^]/,
r,F,M={atom:!0,number:!0,variable:!0,string:!0,regexp:!0,"this":!0};w=m=j=null;x=void 0;var T={name:"this",next:{name:"arguments"}};e.lex=!0;return{startState:function(a){return{tokenize:s,lastType:null,cc:[],lexical:new I((a||0)-q,0,"block",!1),localVars:p.localVars,globalVars:p.globalVars,context:p.localVars&&{vars:p.localVars},indented:0}},token:function(a,d){a.sol()&&(d.lexical.hasOwnProperty("align")||(d.lexical.align=!1),d.indented=a.indentation());if(a.eatSpace())return null;var c=d.tokenize(a,
d);if("comment"==r)return c;d.lastType=r;var b;a:{var e=r,i=F,h=d.cc;j=d;x=a;m=null;w=h;d.lexical.hasOwnProperty("align")||(d.lexical.align=!0);for(;;)if((h.length?h.pop():Q?g:o)(e,i)){for(;h.length&&h[h.length-1].lex;)h.pop()();if(m){b=m;break a}if(b="variable"==e)b:{for(b=d.localVars;b;b=b.next)if(b.name==i){b=!0;break b}b=void 0}if(b){b="variable-2";break a}b=c;break a}}return b},indent:function(a,b){if(a.tokenize==G)return CodeMirror.Pass;if(a.tokenize!=s)return 0;var c=b&&b.charAt(0),f=a.lexical;
"stat"==f.type&&"}"==c&&(f=f.prev);var e=f.type,g=c==e;return"vardef"==e?f.indented+("operator"==a.lastType||","==a.lastType?4:0):"form"==e&&"{"==c?f.indented:"form"==e?f.indented+q:"stat"==e?f.indented+("operator"==a.lastType||","==a.lastType?q:0):"switch"==f.info&&!g?f.indented+(/^(?:case|default)\b/.test(b)?q:2*q):f.align?f.column+(g?0:1):f.indented+(g?0:q)},electricChars:":{}",jsonMode:Q}});CodeMirror.defineMIME("text/javascript","javascript");CodeMirror.defineMIME("text/ecmascript","javascript");
CodeMirror.defineMIME("application/javascript","javascript");CodeMirror.defineMIME("application/ecmascript","javascript");CodeMirror.defineMIME("application/json",{name:"javascript",json:!0});CodeMirror.defineMIME("text/typescript",{name:"javascript",typescript:!0});CodeMirror.defineMIME("application/typescript",{name:"javascript",typescript:!0});