#!/bin/bash
pwd
if [[ $1 != "mysql" && $1 != "postgres" ]] ; then
    echo "This script requires either 'mysql' or 'postgres' as a parameter"
    exit 1
fi

if [[ -d ./vendor/bolt/bolt/ ]] ; then
    echo "This is a Composer install"
    BOLT="./vendor/bolt/bolt"
else
    echo "This is a git install"
    BOLT="."
fi

# Define the config.yml file
CONFIGYML="$BOLT/app/config/config.yml"

echo "Writing new $BOLT/app/config/config.yml"
cat $BOLT/app/config/config.yml.dist > $CONFIGYML

if [[ $1 = "mysql" ]] ; then
    echo "Configuring MySQL in $CONFIGYML"
    perl -p -i -e "undef $/; s/driver: sqlite\n  databasename: bolt/driver: mysql\n  databasename: bolt_travis\n  username: bolt_travis\n  password: bolt_travis/g" $CONFIGYML
elif [[ "$1" = "postgres" ]] ; then
    echo "Configuring PostgreSQL in $CONFIGYML"
    perl -p -i -e "undef $/; s/driver: sqlite\n  databasename: bolt/driver: postgres\n  databasename: bolt_travis\n  username: bolt_travis\n  password: bolt_travis/g" $CONFIGYML
else
    echo "Invalid parameter"
    exit 1
fi
