#!/bin/bash

DB_NAME=bolt_travis
DB_USER=bolt_travis
DB_PASS=bolt_travis

if [[ $1 != "mysql" && $1 != "postgres" ]] ; then
    echo "This script requires either 'mysql' or 'postgres' as a parameter"
    exit 1
fi

if [[ -d ./vendor/bolt/bolt/ ]] ; then
    echo "This is a Composer install"
    BOLT="./vendor/bolt/bolt"
else
    echo "This is a git install"
    BOLT="."
fi

# Define the config.yml file
CONFIGYML="$BOLT/app/config/config.yml"

echo "Writing new $BOLT/app/config/config.yml"
cat $BOLT/app/config/config.yml.dist > $CONFIGYML

if [[ $1 = "mysql" ]] ; then
    echo "Configuring MySQL in $CONFIGYML"
    perl -p -i -e "undef $/; s/driver: sqlite\n    databasename: bolt/driver: mysql\n    databasename: $DB_NAME\n    username: $DB_USER\n    password: $DB_PASS/g" $CONFIGYML
elif [[ "$1" = "postgres" ]] ; then
    echo "Configuring PostgreSQL in $CONFIGYML"
    perl -p -i -e "undef $/; s/driver: sqlite\n    databasename: bolt/driver: postgres\n    databasename: $DB_NAME\n    username: $DB_USER\n    password: $DB_PASS/g" $CONFIGYML
else
    echo "Invalid parameter"
    exit 1
fi
